
version: 2

models:
  - name: dim_violations_by_boro
    description: ""
    columns:
      - name: number_of_violations
        data_type: int64
        description: This field indicates the number of violations that have occured. 

      - name: average_score
        data_type: numeric
        description: This is the average score of the inspections from each borough when violations occurred. 

      - name: borough
        data_type: string
        description: Borough in which the entity (restaurant) is located.

      - name: borough_population
        data_type: int64
        description: The population of each borough in 2020. 

      - name: violations_per_capita
        data_type: float64
        description: The number of violations that occured per capita. 

  - name: fact_inspect_with_pop
    description: ""
    columns:
      - name: violation_id
        data_type: string
        description: Unique value made up of camis_id, inspection_date, and violation_code.  There may be more than 1 violation per restaurant per inspection. 

      - name: camis_id
        data_type: int64
        description: This is an unique identifier for the entity (restaurant); 10-digit integer, static per restaurant permit

      - name: dba
        data_type: string
        description: This field represents the name (doing business as) of the entity (restaurant)

      - name: boro
        data_type: string
        description: Borough in which the entity (restaurant) is located.

      - name: building_number
        data_type: string
        description: Building number for establishment (restaurant) location

      - name: street
        data_type: string
        description: Street name for establishment (restaurant) location

      - name: zipcode
        data_type: string
        description: Zip code of establishment (restaurant) location

      - name: cuisine
        data_type: string
        description: This field describes the entity (restaurant) cuisine.

      - name: insepction_date
        data_type: timestamp
        description: This field represents the date of inspection; Inspection dates of 1/1/1900 mean an establishment has not yet had an inspection

      - name: inspection_performed
        data_type: string
        description: This field indicates if an inspection has or has not yet been performed. 

      - name: action_taken
        data_type: string
        description: This field represents the actions that is associated with each restaurant inspection.

      - name: violation_code
        data_type: string
        description: Violation code associated with an establishment (restaurant) inspection

      - name: violation_description
        data_type: string
        description: Violation description associated with an establishment (restaurant) inspection

      - name: critical_flag
        data_type: string
        description: Indicator of critical violation

      - name: score
        data_type: numeric
        description: Total score for a particular inspection; Scores are updated based on adjudication results

      - name: grade
        data_type: string
        description: Grade associated with the inspection

      - name: grade_date
        data_type: timestamp
        description: The date when the current grade was issued to the entity (restaurant)

      - name: record_date
        data_type: timestamp
        description: The date when the extract was run to produce this data set

      - name: inspection_type
        data_type: string
        description: A combination of the inspection program and the type of inspection performed

      - name: latitude
        data_type: numeric
        description: ""

      - name: longitude
        data_type: numeric
        description: ""

      - name: census_tract
        data_type: string
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: name
        data_type: string
        description: ""

      - name: pop1
        data_type: int64
        description: Population of borough. 

      - name: popacre
        data_type: float64
        description: Population density. 

      - name: landacres
        data_type: int64
        description: Number of acres in each borough. 

  - name: dim_pop_boro
    description: ""
    columns:
      - name: year
        data_type: int64
        description: Census year.

      - name: geotype
        data_type: string
        description: Geographic type.

      - name: borough
        data_type: string
        description: Name of each borough. 

      - name: name
        data_type: string
        description: Name of each area.

      - name: pop1
        data_type: int64
        description: Population.

      - name: popacre
        data_type: float64
        description: Population density.

      - name: landacres
        data_type: int64
        description: Number of acres in each borough. 
